#!/usr/bin/env python3
"""Run the whole pipeline against the booby-trapped corpus and grade it.

Two runs have to pass, and the second is the one that proves portability without
owning a Windows machine:

    verify.py              everything available — PDF wheels, Finder metadata,
                           the OS bin
    verify.py --minimal    every optional capability switched off; the result
                           must stay correct and every gesture still reversible
    verify.py --bare       a config with no rules, no entities, no taxonomy —
                           what a stranger has on day one. The pipeline must
                           still run end to end and refuse to bin anything

Nothing here touches your documents: the corpus, the workspace and the bin all
live in a temporary directory that is removed at the end.

Usage: verify.py [--minimal | --bare] [--keep]
"""
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(SKILL, "fixtures"))
import build as fixtures  # noqa: E402

CONFIG = """\
# generated by verify.py — not an example to copy
workspace: {ws}
root: {root}
language: fr
batch_size: 500

exclude:
  - "*/node_modules/*"
  - "*/.git/*"

identifiers:
  siret: '\\b\\d{{3}}[ .]?\\d{{3}}[ .]?\\d{{3}}[ .]?\\d{{5}}\\b'
  siren: '\\b\\d{{3}}[ .]?\\d{{3}}[ .]?\\d{{3}}\\b'

entities:
  - name: Test Company
    ids: ["123456789"]
    bucket: Company

  - name: Household            # aucun identifiant : reconnue par le texte
    match: {{text_contains_any: [quittance de loyer]}}
    bucket: Personal

  - name: Repreneur
    ids: ["987654321"]
    bucket: Repreneur

sensitive:
  text_contains_any: [passeport, releve d'identite bancaire, iban, bulletin de paie,
                      resultats d'analyses, carte d'identite]
  path_under: [Personal/Identity, Personal/Health]

tags:
  facture: 5
  contrat: 3

review:
  banned_phrases: ["ce document semble", "il s'agit probablement"]

rules:
  - id: rent-receipt
    status: active
    when: {{all: [{{text_contains_any: [quittance de loyer]}}]}}
    level: route
    tag: facture
    destination: "Personal/Housing/rent-receipts-{{doc_year}}"

  - id: invoice
    status: active
    when: {{all: [{{text_contains_any: [facture]}}, {{id_kind_present: [siren, siret]}}]}}
    level: route
    tag: facture
    destination: "{{entity}}/invoices-{{doc_year}}"

  - id: invoice-generic
    status: active
    when: {{all: [{{text_contains_any: [facture, note d'honoraires]}}]}}
    level: route
    tag: facture
    destination: "Company/invoices-{{doc_year}}"

  - id: by-name-only
    status: active
    when: {{all: [{{name_matches: 'never-matches-anything'}}]}}
    level: route
    destination: "Nowhere"

  # en shadow : evaluee, jamais appliquee. Reglee pour DIVERGER — elle envoie
  # les quittances ailleurs que la ou elles vont reellement.
  - id: shadow-candidate
    status: shadow
    passes: 0
    hits: 0
    agreed: 0
    disagreed: 0
    when: {{all: [{{text_contains_any: [quittance de loyer]}}]}}
    level: route
    destination: "Elsewhere"
"""


CONFIG_BARE = """\
# tout ce qu'une installation neuve contient : ou elle vit, ou elle regarde
workspace: {ws}
root: {root}
"""


class Report:
    def __init__(self):
        self.checks = []

    def check(self, name, ok, detail=""):
        self.checks.append({"check": name, "ok": bool(ok), "detail": str(detail)})
        print(f"  {'PASS' if ok else 'FAIL'}  {name}" + (f"  <- {detail}" if detail and not ok else ""))
        return ok

    @property
    def failed(self):
        return [c for c in self.checks if not c["ok"]]


def run(script, *args, ws, minimal, cwd=None):
    env = {**os.environ, "WIKIDOC_HOME": ws}
    if minimal:
        env["WIKIDOC_MINIMAL"] = "1"
    else:
        env.pop("WIKIDOC_MINIMAL", None)
    r = subprocess.run([sys.executable, os.path.join(HERE, script), *args],
                       capture_output=True, text=True, env=env, cwd=cwd or SKILL)
    return r


def jout(r):
    """The scripts print a JSON object first; the rest is human detail."""
    txt = r.stdout.strip()
    start = txt.find("{")
    if start < 0:
        return {}
    depth, end = 0, None
    for i, ch in enumerate(txt[start:], start):
        depth += (ch == "{") - (ch == "}")
        if depth == 0:
            end = i + 1
            break
    try:
        return json.loads(txt[start:end])
    except ValueError:
        return {}


def nfc(s):
    return unicodedata.normalize("NFC", s)


def regressions(rep, tmp):
    """Faults found by having someone else run this, each pinned by a check.

    They share a shape: the pipeline kept working and quietly did the wrong
    thing. None of them would have failed a lane assertion.
    """
    import prepare
    import route as rt
    from close import score_shadows

    # a broken font yields characters but no language, and the document is then
    # filed on nothing at all — a lease went through this way
    rep.check("extractor debris is not mistaken for text",
              not prepare.looks_like_prose("□ □ /2 □ /3 /4 /5 /6 /7 /8 /6 □ /10 /11")
              and not prepare.looks_like_prose("ÅÁgkIYIr<[GgIkZ<h ÈÆÁÂÂ+<gQh ./ÉÉÂÉÉÊ")
              and prepare.looks_like_prose("Compte de gerance periode du 25 juillet au 25 aout")
              and prepare.looks_like_prose("Invoice number and date of issue November 2025"))

    # stripping dots for a SIREN also mangled every address it met
    rep.check("normalising an identifier leaves an email address alone",
              prepare.normalise_id("917 963 183") == "917963183"
              and prepare.normalise_id("agence@syndic-example.fr") == "agence@syndic-example.fr")

    # a guard settles the lane; it must not decide what the rules may learn from
    cfg = {"root": "/r", "entities": [], "sensitive": {"text_contains_any": ["passeport"]},
           "rules": [{"id": "s", "status": "shadow", "level": "route",
                      "destination": "Id", "when": {"all": [{"text_contains_any": ["passeport"]}]}}]}
    guarded = rt.route_entry({"path": "/r/a.txt", "text": "passeport francais"}, cfg, None)
    rep.check("a shadow rule still observes a file a guard caught",
              guarded["rule"].startswith("guard:") and bool(guarded.get("shadow")),
              guarded.get("rule"))

    # counters that never appear are scores silently thrown away
    cpath = os.path.join(tmp, "counters.yaml")
    with open(cpath, "w", encoding="utf-8") as f:
        f.write("rules:\n  - id: r1\n    hits: 47   # trailing comment\n"
                "    when: {}\n  - id: r2\n    when: {}\n")
    rt.bump_counter(cpath, "hits", {"r1": 5, "r2": 3})
    rt.bump_counter(cpath, "disagreed", {"r1": 2})
    written = open(cpath, encoding="utf-8").read()
    rep.check("a counter survives a trailing comment and is created when absent",
              "hits: 52" in written and "hits: 3" in written and "disagreed: 2" in written,
              written)

    # on a corpus that is already tidy — the normal state — a correct rule names
    # the folder the file is already in, and that is agreement, not divergence
    routed = {"files": [{"path": "/r/Bourgville/releve.pdf", "md5": "m",
                         "shadow": [{"rule": "g", "lane": "route", "destination": "/r/Bourgville"}]}]}
    decided = {"m": {"decision": "tag", "path": "Bourgville/releve.pdf", "tags": [], "level": "route"}}
    agreed, disagreed, _, _ = score_shadows(routed, decided, {"root": "/r"})
    rep.check("a rule naming the folder a file is already in counts as agreeing",
              agreed.get("g") == 1 and not disagreed, f"{agreed} {disagreed}")


def main():
    minimal = "--minimal" in sys.argv
    bare = "--bare" in sys.argv
    keep = "--keep" in sys.argv
    tmp = tempfile.mkdtemp(prefix="wikidoc-verify-")
    corpus, ws = os.path.join(tmp, "corpus"), os.path.join(tmp, "workspace")
    os.makedirs(ws)
    rep = Report()
    mode = ("minimal: every optional capability off" if minimal
            else "bare: a config with nothing in it" if bare else "")
    print(f"corpus + workspace in {tmp}" + (f"   [{mode}]" if mode else ""))

    manifest = fixtures.build(corpus)
    with open(os.path.join(tmp, "manifest.json"), "w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=1)
    with open(os.path.join(ws, "config.yaml"), "w", encoding="utf-8") as f:
        f.write((CONFIG_BARE if bare else CONFIG).format(ws=ws, root=corpus))
    # a decoy inside the workspace: the guard must never let it into a batch
    with open(os.path.join(ws, "decoy.txt"), "w", encoding="utf-8") as f:
        f.write("FACTURE decoy — this file lives in the workspace\n")

    print(f"\ntraps built: {json.dumps(manifest['traps'])}\n")

    regressions(rep, tmp)


    # -- 1. prepare ----------------------------------------------------------
    r = run("prepare.py", ws=ws, minimal=minimal)
    prep = jout(r)
    rep.check("prepare runs clean", r.returncode == 0 and prep, r.stderr[-400:])
    expected_files = {nfc(f["path"]) for f in manifest["files"]}
    rep.check("every corpus file reaches the batch",
              prep.get("batch") == len(expected_files),
              f"batch={prep.get('batch')} expected={len(expected_files)}")
    rep.check("no crash on the legacy .doc binaries", prep.get("opaque", 0) >= 4,
              f"opaque={prep.get('opaque')}")

    # -- 2. route ------------------------------------------------------------
    r = run("route.py", ws=ws, minimal=minimal)
    rep.check("route runs clean", r.returncode == 0, r.stderr[-400:])
    routed = json.load(open(os.path.join(ws, "batch", "routed.json"), encoding="utf-8"))
    lanes = {nfc(os.path.relpath(f["path"], corpus)): f for f in routed["files"]}

    rep.check("the workspace decoy never entered the batch",
              not any("decoy.txt" in p for p in lanes), "self-ingestion guard")

    # Lanes are ordered by how much human attention they demand. Losing a
    # capability may push a file to a *more* careful lane — a PDF whose text
    # cannot be extracted becomes residual — and that is a correct degradation.
    # Moving the other way never is.
    CARE = {"route": 0, "propose": 1, "residual": 2, "skip": -1}
    wrong = []
    for f in manifest["files"]:
        got = lanes.get(nfc(f["path"]), {}).get("lane")
        if got is None:
            continue
        ok = got == f["lane"] if not (minimal or bare) else CARE[got] >= CARE[f["lane"]]
        if not ok:
            wrong.append((f["path"], f["lane"], got))
    rep.check("every file lands in its expected lane"
              + (" or a more careful one" if minimal or bare else ""), not wrong, wrong[:6])
    missing = [f["path"] for f in manifest["files"] if nfc(f["path"]) not in lanes]
    rep.check("no file disappears between prepare and route", not missing, missing[:6])

    if bare:
        # Sans une seule regle, le routeur ne prend aucune decision : il ne
        # sait plus que ce que le code garantit — deja-vu, doublon, sans-texte.
        # C'est le mode par defaut d'une installation neuve, et il doit tenir.
        rep.check("with no rules at all, nothing is routed automatically",
                  routed["counts"]["route"] == 0, routed["counts"])
        rep.check("the guards keep working without any config",
                  routed["counts"]["propose"] > 0
                  and all(f["rule"].startswith("guard:")
                          for f in routed["files"] if f.get("rule")),
                  {f["rule"] for f in routed["files"] if f.get("rule")})

    rent = [] if bare else [f for p, f in lanes.items() if f.get("rule") == "rent-receipt"]
    if not bare:
        rep.check("an entity with no identifier still resolves, on its text alone",
                  rent and all(f.get("entity") == "Personal" for f in rent),
                  [f.get("entity") for f in rent[:3]])
    inv = [] if bare else [f for p, f in lanes.items() if f.get("rule") == "invoice"]
    if not bare:
        rep.check("an entity with identifiers resolves on the ids read in the content",
                  inv and all(f.get("entity") == "Company" for f in inv),
                  [f.get("entity") for f in inv[:3]])
        cess = lanes.get("Company/cession-contract.txt", {})
        rep.check("a document claimed by two entities is read, not routed",
                  cess.get("rule") == "guard:entity-ambiguous"
                  and sorted(cess.get("entities") or []) == ["Repreneur", "Test Company"],
                  f"{cess.get('rule')} {cess.get('entities')}")

    # une preuve forte l'emporte sur une preuve faible, quel que soit l'ordre
    # de declaration : Personal est declaree AVANT Repreneur dans le config
    payslips = [f for p, f in lanes.items() if "payslip" in p]
    if not bare:
        rep.check("the strongest evidence wins, not the declaration order",
                  all(f.get("entity") in (None, "Company") for f in payslips),
                  [f.get("entity") for f in payslips[:3]])
        sens = [f for p, f in lanes.items() if f.get("sensitive")]
        rep.check("sensitive documents never route automatically",
                  sens and all(f["lane"] == "propose" for f in sens), len(sens))
        rep.check("a rule matching on the filename alone cannot reach the route lane",
                  all(f["rule"] != "by-name-only" or f["lane"] != "route"
                      for f in lanes.values()))

    if not bare:
        rep.check("a shadow rule never routes anything",
                  all(f.get("rule") != "shadow-candidate" for f in lanes.values()))
        shadowed = [p for p, f in lanes.items()
                    if any(s["rule"] == "shadow-candidate" for s in f.get("shadow", []))]
        rep.check("a shadow rule is recorded on every file it would have caught",
                  len(shadowed) >= (1 if minimal else 12)     # sans texte extrait,
                  and routed["by_shadow"].get("shadow-candidate") == len(shadowed),
                  f"{len(shadowed)} {routed.get('by_shadow')}")   # seul le .txt matche

    dups = [p for p, f in lanes.items() if f.get("duplicate_of")]
    rep.check("byte-identical duplicates are caught", len(dups) == 2, dups)
    rep.check("same text with different bytes is NOT called a duplicate",
              not any("edf-v" in p for p in dups), dups)

    # -- 3. apply: dry run changes nothing -----------------------------------
    movable = [p for p, f in lanes.items()
               if f["lane"] == "route" and f.get("destination")]
    if bare:
        # aucune regle, donc aucune destination : l'agent decide les moves
        # lui-meme, exactement comme il le fera chez quelqu'un sans config
        movable = sorted(p for p, f in lanes.items()
                         if f["lane"] == "residual" and p.startswith("Misc/"))[:3]
        for p in movable:
            lanes[p] = {**lanes[p], "destination": os.path.join(corpus, "Sorted") + os.sep}
    else:
        rep.check("the route lane has work to do",
                  len(movable) >= (3 if minimal else 15), len(movable))
    plan = {"pass": routed["pass"],
            "moves": [{"src": os.path.join(corpus, p),
                       "dst": lanes[p]["destination"],
                       "desc": "Quittance de loyer ou facture, lue dans le texte extrait",
                       "reason": lanes[p].get("rule") or "decide par lecture",
                       "tags": ["facture"]}
                      for p in movable],
            "trash": [{"path": os.path.join(corpus, "Traps/empty.txt"),
                       "reason": "zero bytes"},
                      {"path": os.path.join(corpus, "Personal/Identity/passport-scan.txt"),
                       "reason": "the plan asks for a sensitive file: must be refused",
                       "text": "PASSEPORT Republique Francaise"}],
            "keep": [{"path": os.path.join(corpus, "Misc/notes.txt"),
                      "desc": "Note manuscrite sans valeur administrative",
                      "reason": "already-well-filed"}]}
    plan_path = os.path.join(tmp, "plan.json")
    with open(plan_path, "w", encoding="utf-8") as f:
        json.dump(plan, f, ensure_ascii=False)

    before = {p: os.stat(os.path.join(corpus, p)).st_mtime
              for p in movable if os.path.exists(os.path.join(corpus, p))}
    r = run("apply.py", plan_path, ws=ws, minimal=minimal)
    after = {p: os.stat(os.path.join(corpus, p)).st_mtime
             for p in movable if os.path.exists(os.path.join(corpus, p))}
    rep.check("dry run leaves every file where it was", before == after)
    rep.check("dry run writes no ledger line",
              not os.path.exists(os.path.join(ws, "ledger.jsonl")))

    # -- 4. apply --execute --------------------------------------------------
    # forced minimal so the bin fallback is exercised and the real Trash stays clean
    r = run("apply.py", plan_path, "--execute", ws=ws, minimal=True)
    applied = jout(r)
    rep.check("moves are confirmed at destination",
              applied.get("applied", {}).get("move") == len(movable) if movable
              else True,
              f"{applied.get('applied')} failed={applied.get('failed')}")
    passport = os.path.join(corpus, "Personal/Identity/passport-scan.txt")
    binned = os.path.join(ws, ".trash")
    recovered = [os.path.join(dp, f) for dp, _, fs in os.walk(binned) for f in fs] \
        if os.path.isdir(binned) else []
    if bare:
        rep.check("with no `sensitive:` declared, nothing is binned at all",
                  os.path.exists(passport)
                  and os.path.exists(os.path.join(corpus, "Traps/empty.txt"))
                  and not recovered, recovered)
    else:
        rep.check("the sensitive file survives a plan that asked to bin it",
                  os.path.exists(passport) and "sensitive" in r.stdout)
        rep.check("a binned file is recoverable, never unlinked",
                  len(recovered) == 1, recovered)
    rep.check("the ledger records the pass",
              os.path.exists(os.path.join(ws, "ledger.jsonl")))

    # -- 5. close ------------------------------------------------------------
    r = run("close.py", "--note", "decision | test corpus: a blank form is a KEEP",
            ws=ws, minimal=minimal)
    rep.check("close runs clean", r.returncode == 0, r.stdout[-400:] + r.stderr[-400:])
    if not bare:
        rep.check("close reports the shadow rule that diverged from the decisions",
                  "shadow-candidate" in r.stdout and "diverged" in r.stdout,
                  r.stdout[-300:])
        cfg_after = open(os.path.join(ws, "config.yaml"), encoding="utf-8").read()
        rep.check("the divergence is written back into the rule's record",
                  re.search(r"disagreed: [1-9]", cfg_after) is not None,
                  [l for l in cfg_after.splitlines() if "disagreed" in l])
    rep.check("the bench is empty between passes",
              not os.listdir(os.path.join(ws, "batch")), os.listdir(os.path.join(ws, "batch")))
    rep.check("the journal takes the arbitration",
              os.path.exists(os.path.join(ws, "journal.md"))
              and "decision" in open(os.path.join(ws, "journal.md"), encoding="utf-8").read())

    ledger_lines = [json.loads(l) for l in
                    open(os.path.join(ws, "ledger.jsonl"), encoding="utf-8")]
    seen_paths = {r["path"] for r in ledger_lines}
    rep.check("every file of the pass has a ledger line",
              len(seen_paths) >= len(expected_files) - len(recovered) - 2,
              f"{len(seen_paths)} lines for {len(expected_files)} files")
    rep.check("non-actions carry their reason",
              any(r["decision"] == "none" and r.get("reason") for r in ledger_lines))

    # -- 6. the regression pass ---------------------------------------------
    r = run("prepare.py", ws=ws, minimal=minimal)
    again = jout(r)
    rep.check("a second pass proposes nothing already processed",
              again.get("batch", -1) == 0,
              f"batch={again.get('batch')} already_in_ledger={again.get('already_in_ledger')}")

    # -- 7. optional capabilities -------------------------------------------
    if not minimal:
        caps = {}
        for mod in ("pypdf", "pypdfium2", "send2trash", "striprtf", "yaml"):
            try:
                __import__(mod)
                caps[mod] = True
            except ImportError:
                caps[mod] = False
        rep.check("PDF text extraction is available", caps["pypdf"], caps)
        rep.check("the OS bin is available", caps["send2trash"], caps)

    print("\n" + json.dumps({"mode": "minimal" if minimal else "bare" if bare else "full",
                             "checks": len(rep.checks),
                             "failed": len(rep.failed),
                             "traps": manifest["traps"]}, ensure_ascii=False, indent=1))
    for c in rep.failed:
        print(f"  FAIL {c['check']}: {c['detail']}")
    if keep:
        print(f"\nkept: {tmp}")
    else:
        shutil.rmtree(tmp, ignore_errors=True)
    sys.exit(1 if rep.failed else 0)


if __name__ == "__main__":
    main()
